server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://49.235.67.7:18080/eureka/ #注册另外一个注册中心
    enabled: true #开启、关闭eureka

  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 60
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${random.int(10)}
    metadata-map:
      zone: shanghai #指定实例的zone，用于Ribbon的区域亲和策略
    ip-address: 101.37.172.37 #服务部署主机的外网ip地址（确保其他服务能访问到）
    non-secure-port: 18081 #服务部署主机的外网端口（确保其他服务能够访问到）