spring:
  datasource:
    #  第二个数据源
    oracle:
      jdbc-url: jdbc:oracle:thin:@localhost:1521:orac
      username: system
      password: 123456
      driver-class-name: oracle.jdbc.driver.OracleDriver