module SpringBootLearn {
    // requires expenses.readers;
    requires org.aspectj.weaver;
    requires spring.context;
    requires spring.web;
    requires spring.tx;
    requires spring.data.jpa;
    requires lombok;
    requires java.persistence;
    requires spring.data.elasticsearch;
    requires spring.data.commons;
    requires spring.cloud.openfeign.core;
    requires feign.core;
    requires org.hibernate.orm.core;
    requires jackson.annotations;
    requires zookeeper;
    requires spring.boot;
    requires java.sql;
    requires spring.orm;
    requires spring.beans;
    requires spring.kafka;
    requires spring.messaging;
    requires java.validation;
    requires spring.boot.autoconfigure;
    requires java.annotation;
    requires debezium.api;
    requires kafka.clients;
    requires spring.data.redis;
    requires spring.test;
    requires junit;
    requires spring.boot.test;
    requires spring.core;
    requires spring.expression;
    requires org.apache.httpcomponents.httpclient;
    requires org.apache.httpcomponents.httpcore;
    requires spring.security.core;
    requires tomcat.embed.core;
    requires spring.websocket;
    requires quartz;
    requires spring.webmvc;
    // requires elasticsearch.rest.high.level.client;
    requires fastjson;
    requires elasticsearch.x.content;
    requires hutool.all;
    requires elasticsearch.rest.client;
    requires elasticsearch;
}